


// This file is automatically generated.
// It is not in the generated folder for ease-of-use (no relative paths).
// This file must remain in place relative to the generated scripts (<WebProject>/Scripts/Generated).



/// <reference path="coalesce.dependencies.d.ts" />
/// <reference path="Generated\Ko.ApplicationUser.ts" />
/// <reference path="Generated\Ko.ApplicationUserList.ts" />
/// <reference path="Generated\Ko.Course.ts" />
/// <reference path="Generated\Ko.CourseList.ts" />
/// <reference path="Generated\Ko.Enrollment.ts" />
/// <reference path="Generated\Ko.EnrollmentList.ts" />
/// <reference path="Generated\Ko.Instructor.ts" />
/// <reference path="Generated\Ko.InstructorList.ts" />
/// <reference path="Generated\Ko.Student.ts" />
/// <reference path="Generated\Ko.StudentList.ts" />
