


// This file is automatically generated.
// It is not in the generated folder for ease-of-use (no relative paths).
// This file must remain in place relative to the generated scripts (<WebProject>/Scripts/Generated).



/// <reference path="coalesce.dependencies.d.ts" />
/// <reference path="Generated\Ko.Author.ts" />
/// <reference path="Generated\Ko.AuthorList.ts" />
/// <reference path="Generated\Ko.Blog.ts" />
/// <reference path="Generated\Ko.BlogAndAuthor.ts" />
/// <reference path="Generated\Ko.BlogAndAuthorList.ts" />
/// <reference path="Generated\Ko.BlogList.ts" />
/// <reference path="Generated\Ko.BlogsWithNameFoo.ts" />
/// <reference path="Generated\Ko.BlogsWithNameFooList.ts" />
/// <reference path="Generated\Ko.ShortBlog.ts" />
/// <reference path="Generated\Ko.ShortBlogList.ts" />
